<a href="https://colab.research.google.com/github/tak-creator/Colab-Lab/blob/main/pandas_tutotial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import seaborn as sns

In [ ]:
pd.DataFrame({'Yes': [50, 21], 'No': [131, 2]})

   Yes   No
0   50  131
1   21    2

In [ ]:
pd.DataFrame({'Bob': ['I liked it.', 'It was awful.'], 'Sue': ['Pretty good.', 'Bland.']})

             Bob           Sue
0    I liked it.  Pretty good.
1  It was awful.        Bland.

In [ ]:
pd.DataFrame({'Bob': ['I liked it.', 'It was awful.'],
              'Sue': ['Pretty good.', 'Bland.']},
             index=['Product A', 'Product B'])

                     Bob           Sue
Product A    I liked it.  Pretty good.
Product B  It was awful.        Bland.

In [ ]:
pd.DataFrame({'Product_A': [30, 35, 40]}, index=['2015', '2016', '2017'])

      Product_A
2015         30
2016         35
2017         40

In [ ]:
pd.DataFrame({'Prd A':[1, 2, 3, 4, 5],
           'Prd B':[6, 7, 8, 9, 10]},
          index=['a', 'b', 'c', 'd', 'e'])

   Prd A  Prd B
a      1      6
b      2      7
c      3      8
d      4      9
e      5     10

In [ ]:
pd.Series([1, 2, 3, 4, 5], name='Name')

0    1
1    2
2    3
3    4
4    5
Name: Name, dtype: int64

In [ ]:
fruits = pd.DataFrame([[30, 21]], columns=['Apples', 'Bananas'])

fruits

   Apples  Bananas
0      30       21

In [ ]:
#top_oceania_wines = reviews.loc[
    #(reviews.country.isin(['Australia', 'New Zealand']))
    #& (reviews.points >= 95)
#]

In [ ]:
df = sns.load_dataset('titanic')
print(df.head(10))

   survived  pclass     sex   age  sibsp  parch     fare embarked   class  \
0         0       3    male  22.0      1      0   7.2500        S   Third
1         1       1  female  38.0      1      0  71.2833        C   First
2         1       3  female  26.0      0      0   7.9250        S   Third
3         1       1  female  35.0      1      0  53.1000        S   First
4         0       3    male  35.0      0      0   8.0500        S   Third
5         0       3    male   NaN      0      0   8.4583        Q   Third
6         0       1    male  54.0      0      0  51.8625        S   First
7         0       3    male   2.0      3      1  21.0750        S   Third
8         1       3  female  27.0      0      2  11.1333        S   Third
9         1       2  female  14.0      1      0  30.0708        C  Second

     who  adult_male deck  embark_town alive  alone
0    man        True  NaN  Southampton    no  False
1  woman       False    C    Cherbourg   yes  False
2  woman       False  NaN  Southampton   yes   True
3  woman       False    C  Southampton   yes  False
4    man        True  NaN  Southampton    no   True
5    man        True  NaN   Queenstown    no   True
6    man        True    E  Southampton    no   True
7  child       False  NaN  Southampton    no  False
8  woman       False  NaN  Southampton   yes  False
9  child       False  NaN    Cherbourg   yes  False

In [ ]:
df.fare.describe()

count    891.000000
mean      32.204208
std       49.693429
min        0.000000
25%        7.910400
50%       14.454200
75%       31.000000
max      512.329200
Name: fare, dtype: float64

In [ ]:
df['embark_town'].describe()

count             889
unique              3
top       Southampton
freq              644
Name: embark_town, dtype: object

In [ ]:
print(df.fare.mean())

32.204207968574636

In [ ]:
df.embark_town.unique()

array(['Southampton', 'Cherbourg', 'Queenstown', nan], dtype=object)

In [ ]:
df.embark_town.value_counts()

embark_town
Southampton    644
Cherbourg      168
Queenstown      77
Name: count, dtype: int64

`df.fare.map(lambda p: p - df_fare_mean)` dla każdej wartości p w serii fare wywołuje funkcję, która zwraca różnicę między tą wartością a uprzednio obliczoną średnią, czyli tworzy nową serię odchyleń od wartości średnie

In [ ]:
df_fare_mean = df.fare.mean()
print(df.fare.map(lambda p: p - df_fare_mean))
print('\n')     # to samo
print(df.fare - df_fare_mean)

0     -24.954208
1      39.079092
2     -24.279208
3      20.895792
4     -24.154208
         ...
886   -19.204208
887    -2.204208
888    -8.754208
889    -2.204208
890   -24.454208
Name: fare, Length: 891, dtype: float64


0     -24.954208
1      39.079092
2     -24.279208
3      20.895792
4     -24.154208
         ...
886   -19.204208
887    -2.204208
888    -8.754208
889    -2.204208
890   -24.454208
Name: fare, Length: 891, dtype: float64

In [ ]:
def remean_points(row):
    row.fare = row.fare - df_fare_mean
    return row

df.apply(remean_points, axis='columns')

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,-24.954208,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,39.079092,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,-24.279208,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,20.895792,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,-24.154208,S,Third,man,True,NaN,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,-19.204208,S,Second,man,True,NaN,Southampton,no,True
887,1,1,female,19.0,0,0,-2.204208,S,First,woman,False,B,Southampton,yes,True
888,0,3,female,NaN,1,2,-8.754208,S,Third,woman,False,NaN,Southampton,no,False
889,1,1,male,26.0,0,0,-2.204208,C,First,man,True,C,Cherbourg,yes,True
890,0,3,male,32.0,0,0,-24.454208,Q,Third,man,True,NaN,Queenstown,no,True

In [ ]:
print(df.embark_town + " - " + df.alive)

0       Southampton - no
1        Cherbourg - yes
2      Southampton - yes
3      Southampton - yes
4       Southampton - no
             ...
886     Southampton - no
887    Southampton - yes
888     Southampton - no
889      Cherbourg - yes
890      Queenstown - no
Length: 891, dtype: object

Znalezienie indeksu maksymalnego stosunku `fare/age`

In [ ]:
df_clean = df.dropna(subset=['fare', 'age'])
df_idx = (df_clean.fare / df_clean.age).idxmax()
df_passenger = df.loc[df_idx, ['who', 'fare', 'age']]

print(f"Najwyższy wskaźnik fare/age ma pasażer o indeksie {df_idx}:")
print(f"  Typ: {df_passenger['who']}, Fare: {df_passenger['fare']}, Age: {df_passenger['age']}")

Najwyższy wskaźnik fare/age ma pasażer o indeksie 305:
  Typ: child, Fare: 151.55, Age: 0.92

In [ ]:
df.groupby('who').who.count()

who
child     83
man      537
woman    271
Name: who, dtype: int64

In [ ]:
df.groupby('age').fare.min()

age
0.42       8.5167
0.67      14.5000
0.75      19.2583
0.83      18.7500
0.92     151.5500
           ...
70.00     10.5000
70.50      7.7500
71.00     34.6542
74.00      7.7750
80.00     30.0000
Name: fare, Length: 88, dtype: float64

In [ ]:
df.groupby('fare').apply(lambda df: df.deck.iloc[0])

<ipython-input-22-33fc2be9234f>:1: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  df.groupby('fare').apply(lambda df: df.deck.iloc[0])

fare
0.0000      NaN
4.0125      NaN
5.0000        B
6.2375      NaN
6.4375      NaN
           ...
227.5250    NaN
247.5208      B
262.3750      B
263.0000      C
512.3292    NaN
Length: 248, dtype: object

In [ ]:
df.groupby(['embark_town', 'sex']).apply(lambda df: df.loc[df.fare.idxmax()])

<ipython-input-23-dc6771fddd42>:1: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  df.groupby(['embark_town', 'sex']).apply(lambda df: df.loc[df.fare.idxmax()])

                    survived  pclass     sex   age  sibsp  parch      fare  \
embark_town sex
Cherbourg   female         1       1  female  35.0      0      0  512.3292
            male           1       1    male  36.0      0      1  512.3292
Queenstown  female         1       1  female  33.0      1      0   90.0000
            male           0       1    male  44.0      2      0   90.0000
Southampton female         1       1  female  23.0      3      2  263.0000
            male           0       1    male  19.0      3      2  263.0000

                   embarked  class    who  adult_male deck  embark_town alive  \
embark_town sex
Cherbourg   female        C  First  woman       False  NaN    Cherbourg   yes
            male          C  First    man        True    B    Cherbourg   yes
Queenstown  female        Q  First  woman       False    C   Queenstown   yes
            male          Q  First    man        True    C   Queenstown    no
Southampton female        S  First  woman       False    C  Southampton   yes
            male          S  First    man        True    C  Southampton    no

                    alone
embark_town sex
Cherbourg   female   True
            male    False
Queenstown  female  False
            male    False
Southampton female  False
            male    False

In [ ]:
df.groupby(['embark_town']).fare.agg([len, min, max])

<ipython-input-24-61c55d9e6090>:1: FutureWarning: The provided callable <built-in function min> is currently using SeriesGroupBy.min. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "min" instead.
  df.groupby(['embark_town']).fare.agg([len, min, max])
<ipython-input-24-61c55d9e6090>:1: FutureWarning: The provided callable <built-in function max> is currently using SeriesGroupBy.max. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "max" instead.
  df.groupby(['embark_town']).fare.agg([len, min, max])

             len     min       max
embark_town
Cherbourg    168  4.0125  512.3292
Queenstown    77  6.7500   90.0000
Southampton  644  0.0000  263.0000

In [ ]:
df_reviewed = df.groupby(['embark_town', 'age']).who.agg([len])
df_reviewed

                   len
embark_town age
Cherbourg   0.42     1
            0.75     2
            1.00     2
            3.00     1
            4.00     1
...                ...
Southampton 65.00    1
            66.00    1
            70.00    2
            74.00    1
            80.00    1

[162 rows x 1 columns]

In [ ]:
mi = df_reviewed.index
type(mi)

pandas.core.indexes.multi.MultiIndex

In [ ]:
df_reviewed.reset_index()

     embark_town    age  len
0      Cherbourg   0.42    1
1      Cherbourg   0.75    2
2      Cherbourg   1.00    2
3      Cherbourg   3.00    1
4      Cherbourg   4.00    1
..           ...    ...  ...
157  Southampton  65.00    1
158  Southampton  66.00    1
159  Southampton  70.00    2
160  Southampton  74.00    1
161  Southampton  80.00    1

[162 rows x 3 columns]

In [ ]:
df_reviewed = df_reviewed.reset_index()
df_reviewed.sort_values(by='len')

     embark_town    age  len
0      Cherbourg   0.42    1
3      Cherbourg   3.00    1
5      Cherbourg   5.00    1
4      Cherbourg   4.00    1
6      Cherbourg   9.00    1
..           ...    ...  ...
101  Southampton  18.00   21
105  Southampton  21.00   21
102  Southampton  19.00   22
113  Southampton  28.00   23
108  Southampton  24.00   23

[162 rows x 3 columns]

In [ ]:
df_reviewed.sort_values(by='len', ascending=False)

     embark_town   age  len
113  Southampton  28.0   23
108  Southampton  24.0   23
102  Southampton  19.0   22
101  Southampton  18.0   21
105  Southampton  21.0   21
..           ...   ...  ...
147  Southampton  55.5    1
157  Southampton  65.0    1
158  Southampton  66.0    1
160  Southampton  74.0    1
161  Southampton  80.0    1

[162 rows x 3 columns]

In [ ]:
df_reviewed.sort_index()

     embark_town    age  len
0      Cherbourg   0.42    1
1      Cherbourg   0.75    2
2      Cherbourg   1.00    2
3      Cherbourg   3.00    1
4      Cherbourg   4.00    1
..           ...    ...  ...
157  Southampton  65.00    1
158  Southampton  66.00    1
159  Southampton  70.00    2
160  Southampton  74.00    1
161  Southampton  80.00    1

[162 rows x 3 columns]

In [ ]:
df_reviewed.sort_values(by=['embark_town', 'age'])

     embark_town    age  len
0      Cherbourg   0.42    1
1      Cherbourg   0.75    2
2      Cherbourg   1.00    2
3      Cherbourg   3.00    1
4      Cherbourg   4.00    1
..           ...    ...  ...
157  Southampton  65.00    1
158  Southampton  66.00    1
159  Southampton  70.00    2
160  Southampton  74.00    1
161  Southampton  80.00    1

[162 rows x 3 columns]

In [ ]:
df[pd.isnull(df.deck)]

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
5,0,3,male,NaN,0,0,8.4583,Q,Third,man,True,NaN,Queenstown,no,True
7,0,3,male,2.0,3,1,21.0750,S,Third,child,False,NaN,Southampton,no,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
884,0,3,male,25.0,0,0,7.0500,S,Third,man,True,NaN,Southampton,no,True
885,0,3,female,39.0,0,5,29.1250,Q,Third,woman,False,NaN,Queenstown,no,False
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True

In [ ]:
df[pd.notnull(df.deck)]

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
6,0,1,male,54.0,0,0,51.8625,S,First,man,True,E,Southampton,no,True
10,1,3,female,4.0,1,1,16.7000,S,Third,child,False,G,Southampton,yes,False
11,1,1,female,58.0,0,0,26.5500,S,First,woman,False,C,Southampton,yes,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
871,1,1,female,47.0,1,1,52.5542,S,First,woman,False,D,Southampton,yes,False
872,0,1,male,33.0,0,0,5.0000,S,First,man,True,B,Southampton,no,True
879,1,1,female,56.0,0,1,83.1583,C,First,woman,False,C,Cherbourg,yes,False
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True

In [ ]:
df.index.dtype

dtype('int64')

In [ ]:
df.fare.astype('float64')

0       7.2500
1      71.2833
2       7.9250
3      53.1000
4       8.0500
        ...
886    13.0000
887    30.0000
888    23.4500
889    30.0000
890     7.7500
Name: fare, Length: 891, dtype: float64

In [ ]:
n_missing_prices = df.deck.isnull().sum()
print(f"Liczba brakujących wartości w kolumnie fare: {n_missing_prices}")

Liczba brakujących wartości w kolumnie fare: 688

In [ ]:
#reviews_per_region = reviews.region_1.fillna('Unknown').value_counts().sort_values(ascending=False)

In [ ]:
df.rename(columns={'fare': 'price'})

,survived,pclass,sex,age,sibsp,parch,price,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True

In [ ]:
df.rename(index={0: 'zeroEntry', 1: 'firstEntry'})

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
zeroEntry,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
firstEntry,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True

In [ ]:
df.rename_axis('joł', axis='rows').rename_axis('uga buga', axis='columns')

uga buga,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
joł,,,,,,,,,,,,,,,
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True

`canadian_youtube = pd.read_csv("../input/youtube-new/CAvideos.csv")`
`british_youtube = pd.read_csv("../input/youtube-new/GBvideos.csv")`

pd.**concat**([canadian_youtube, british_youtube])

left = canadian_youtube.set_index(['title', 'trending_date'])
right = british_youtube.set_index(['title', 'trending_date'])

left.join(right, lsuffix='_CAN', rsuffix='_UK')